#
esphome:
  name: powerreporter

esp32:
  board: az-delivery-devkit-v4 #esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret ha_api_password

ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ssid
    password: !secret fallback_password

captive_portal:



##########################################################################
# Wiring
#
#                    
#    0V ---------+                           +------ LI.RX
#                |                           |   +-- LI.TX
#   +5V  ----+   |                           |   |
#            |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
#        +---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
#        |   Vin Gnd D13 D12 D14 D27 D26 D25 D33 D32 D35 D34 Vn  Vp  En  |
#        |           MOS MIS CLK                                         |
#        |                                                               |
#        |                                                               |
#        |         SPI                     CLK MIS         UAR UAR MOS   |
#        |          CS         RX2 TX2     SPI SPI         RX0 TX0 SPI   |
#        | 3v3 Gnd D15  D2  D4 D16 D17  D5 D18 D19 D21 D03 D01 D22 D23   |
#        +---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+---+
#            |   |   |   |   |   |   |   |   |   |   |   |   |   |   |
#                |   |   |   |   |   |   |   |   |   |   |           |
#    0V ---------+   |   |   |   |   |   |   |   |   |               |
#                |   |   |   |   |   |   |   |   |   |               |
#                |   |   |   |   +   +   +   |   |   |               |
#                |   |   |   | RS.RO  RS.DERE|   |   |               |
#                |   |   |   |     RS.DI     |   |   |               |
#                |   |   |   |               |   |   |               |
#                |   |   |   |   +-----------/---+   |               |
#                |   |   |   |   |           |       |               |
#                |   |   |   |   |   +-------+       |               |         
#                |   |   |   |   |   |               |               |
#                |   |   |   |   |   |   +-----------+               |
#                |   |   |   |   |   |   |                           |
#                |   |   |   |   |   |   |   +-----------------------+
#                |   |   |   |   |   |   |   |          
#         ILI   2+  3+  4+  5+  6+  7+  8+  9+                  
#         ILI    2   3   4   5   6   7   8   9                  
#             GND| CS|RST| DC|MOS|CLK|LED|MIS|                 
#
#  ILI TFT 2.2                                       MAX3485
#      
#       +5V --1- VCC                                    3V3 - VCC
#        0V --2- GND                                     0V - GND
#   ESP.D15 --3- CS                              ESP.D16 RX - RO
#   ESP.D2  --4- RESET                           ESP.D05    - RE/DE 
#   ESP.D4  --5- DC/RS                           ESP.D17 TX - DI
#   ESP.D19 --6- MOSI/SDI
#   ESP.D18 --7- SCLK
#   ESP.D27 --8- LED
#   ESP.D23 --9- MISO/SDO
#
#
packages:
  me3000: !include
    file: powerreporter-packages/me3000.yaml
    vars:
      uart_rx: GPIO16
      uart_tx: GPIO17
      flow_control: GPIO5
      modbus_address: 0x01

  teleinfo: !include
    file: powerreporter-packages/teleinfo.yaml
    vars:
       linky_rx: GPIO33
       linky_tx: GPIO32
       linky_speed: 1200
       linky_histo: true
  display: !include
    file: powerreporter-packages/display.yaml
    vars:
       disp_clk_pin: GPIO18 # GPIO18
       disp_mosi_pin: GPIO19 # GPIO23
       disp_miso_pin: GPIO23 # GPIO19
       disp_dc_pin: GPIO4 # GPIO21
       disp_cs_pin: GPIO15 # GPIO22
       disp_reset_pin: GPIO2 # GPIO17
