# POWER REPORTER
#
# Sends data from Sofar Solar ME300 and Link to Homeassistant
#
# This is the ESP32-S2 mini version
# Specificities: ESP32-S2 has only 2 UARTs
#
esphome:
  name: powerreporter
  platformio_options:
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0" # Allow boh UART to be used with arduino build chain

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino
#    type: esp-idf # recommended for ESP32S2
#    version: recommended
#    # Custom sdkconfig options
#    sdkconfig_options:
#      COMPILER_OPTIMIZATION_SIZE: y
#    # Advanced tweaking options
#    advanced:
#      ignore_efuse_mac_crc: false

# Disable logging to ensure both IARTs are free to use.
logger:
  baud_rate: 0
#  level: NONE

# Enable Home Assistant API
api:
  password: !secret ha_api_password

ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ssid
    password: !secret fallback_password

captive_portal:



##########################################################################
# Wiring
#
#                    
#    0V ----------+                           +------ LI.RX
#                |                           |   +-- LI.TX
#   +5V  ----+   |                           |   |
#            |   |   |   |   |   |   |   |   |   |   |   |   |   |  |
#            | |    | |    | |    | |    | |    | |    | |    | |   
#        +---+-|----+-|----+-|----+-|----+-|----+-|----+-|----+-|----+
#        |   | |    | |    | |    | |    | |    | |    | |    | |    |
#        |   Vin Gnd D13 D12 D14 D27 D26 D25 D33 D32 D35 D34 Vn  |  En  |
#        |           MOS MIS CLK                                 +      |
#        |                                                       1      |
#        |                                                           |
#        |---+                                                       |
#        | U |                                                       |
#        | S |            S2 MINI                                    |
#        | B |                                                       |
#        |---+                                                       |
#        |                                                           |
#        | D15-+  Gnd-+  D17-+  D21-+  D34-+  D36-+  D38-+  D40-+    | 
#        |     |      |      |      |      |      |      |      |    |
#        |VBUS |   Gnd|  D16 |  D18 |   D33|  D35 |  D37 |  D39 |    |
#        |   | |    | |    | |    | |    | |    | |    | |    | |    |
#        +---+-|----+-|----+-|----+-|----+-|----+-|----+-|----+-|----+
#            | |    | |    | |    | |    | |    | |    | |    | |   
#              |    | |    | |    | |    | |    | |    | |    | |   
#    0V ------------+ |    | |    |      | |    | |    | |      |
#                          | |    |      | |    | |    | |      |   
#                          | |    |      | |    | |    | |      |   
#             MAX485.RO ---+ |    |      | |    | |    | |      |   
#                            |    |      | |    | |    | |      |   
#             MAX485.DI -----+    |      +-|+   | |    +----+   |
#                                 |        ||   | |      |  |   |
#           MAX485.REDE ----------+        ||   | |     ++  |   |
#                                          ||   | +-+   |   |   |
#                                   +------+|   |   |   |   |   |
#                                   |   +---|-------------------+
#                                   |   |   |   |   |   |   |
#                           |   |   |   |   |   |   |   |   |          
#                           1   2   3   4   5   6   7   8   9                  
#                        VCC|GND| CS|RST| DC|MOS|CLK|LED|MIS|                 
#
#  ILI TFT 2.2                                       MAX3485
#      
#           +5V --1- VCC                                    3V3 - VCC
#            0V --2- GND                                     0V - GND
#   ESP32S2.D34 --3- CS                              ESP.D16 RX - RO
#   ESP32S2.D40 --4- RESET                           ESP.D18    - RE/DE 
#   ESP32S2.D33 --5- DC/RS                           ESP.D17 TX - DI
#   ESP32S2.D35 --6- MOSI/SDI
#   ESP32S2.D36 --7- SCLK
#   ESP32S2.D38 --8- LED
#   ESP32S2.D37 --9- MISO/SDO
#
#
packages:
  me3000: !include
    file: powerreporter-packages/me3000.yaml
    vars:
      uart_rx: GPIO21 # GPIO16
      uart_tx: GPIO16 # GPIO17
      flow_control: GPIO18
      modbus_address: 0x01

  teleinfo: !include
    file: powerreporter-packages/teleinfo.yaml
    vars:
       linky_rx: GPIO9
       linky_tx: GPIO10
       linky_speed: 1200
       linky_histo: true

  display: !include
    file: powerreporter-packages/display.yaml
    vars:
       disp_clk_pin: GPIO36
       disp_mosi_pin: GPIO35
       disp_miso_pin: GPIO37
       disp_dc_pin: GPIO33
       disp_cs_pin: GPIO34
       disp_reset_pin: GPIO40
